### ISSUE TITLE
How to set up with docker-compose?

### ISSUE THREAD

**Issue by phischmi** [bwssytems/ha-bridge#1055]
Hi all,
i just tried to setup ha-bridge with docker-compose:
```
ha-bridge:
    image: habridge/ha-bridge-raspberrypi3
    restart: always
    network_mode: host
    volumes:
      - ./docker/ha-bridge/data/:/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      JAVA_OPTS: '-Dserver.port=8082'
```
But the last part doesn't seem to work, as ha-birdge always tries to create the webservice on port 80 instead of 8082

How to pass these arguments correctly using docker-compose?
