### ISSUE TITLE
rgb support for HomeAssistant

### ISSUE THREAD

**Issue by ReneHezser** [bwssytems/ha-bridge#1294]
I am unable to set the color on my Yeelight YLDL01YL Meteorite light.
HomeAssistant does support it with its Yeelight integration and setting the color does work.
```yaml
service: light.turn_on
data:
  entity_id: light.yeelight_ceiling10_0xyz_ambilight
  rgb_color:
    - 0
    - 255
    - 0
```

On, Off and Dim does work with "HomeAssistant Device" type.
```json
{"entityId":"light.yeelight_ceiling10_0xyz_ambilight","hassName":"Home Assistant","state":"on"}
{"entityId":"light.yeelight_ceiling10_0xyz_ambilight","hassName":"Home Assistant","state":"on","bri":"${intensity.percent}"}
{"entityId":"light.yeelight_ceiling10_0xyz_ambilight","hassName":"Home Assistant","state":"off"}
```
Is setting the rgb color supported? I can't find it on the documentation or an example.
