### ISSUE TITLE
Can't connect via Hue Essentials

### ISSUE THREAD

**Issue by stefpb** [bwssytems/ha-bridge#1305]
after a start with docker-compose like that:
```
  habridge:
    image: ghcr.io/linuxserver/habridge
    container_name: habridge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./config/habridge:/config
    network_mode: 'host'
    restart: unless-stopped
```
with nothing special config or web configuration. Than i take my Android Phone with the Hue Essential App, choose Devices -> Add -> Bridges -> Hue -> my IP and Port 8000 i get a _Bridge is not reachable. Please check your internet connection._

In the server log i get this message
```
habridge    | 2056-07-27 05:08:56.000:WARN:oejh.HttpParser:qtp3959093-8: Illegal character 0x16 in state=START for buffer HeapByteBuffer@99c74f[p=1,l=251,c=8192,r=250]={\x16<<<\x03\x01\x00\xF6\x01\x00\x00\xF2\x03\x03\xDb k\x02\x8c\x8c\x90...\x00-\x00\x02\x01\x01\x00+\x00\x05\x04\x03\x04\x03\x03>>>NT: 1\r\nReferer: h...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
habridge    | 2055-08-10 01:44:08.000:WARN:oejh.HttpParser:qtp3959093-25: Illegal character 0x16 in state=START for buffer HeapByteBuffer@99c74f[p=1,l=251,c=8192,r=250]={\x16<<<\x03\x01\x00\xF6\x01\x00\x00\xF2\x03\x03\x11q\xC7\x06\xA3\xCd\xFf...\x00-\x00\x02\x01\x01\x00+\x00\x05\x04\x03\x04\x03\x03>>>NT: 1\r\nReferer: h...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
```

I tried hours with different configurations and researches. Want is wrong?
